/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topupit.assignment;

/**
 *
 * @author tahmid
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        userLogin = new javax.swing.JLabel();
        movieSchedule = new javax.swing.JLabel();
        upcomingMovies = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multiplex Management System");
        setForeground(java.awt.Color.lightGray);

        jPanel1.setBackground(new java.awt.Color(71, 71, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Multiplex Management System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(215, 90, 74))); // NOI18N
        jPanel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        title.setFont(new java.awt.Font("Palatino Linotype", 1, 30)); // NOI18N
        title.setForeground(new java.awt.Color(224, 224, 206));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topupit/assignment/network-64px.png"))); // NOI18N
        title.setText("Multiplex Management System");
        title.setToolTipText("");

        userLogin.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        userLogin.setForeground(new java.awt.Color(242, 175, 41));
        userLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topupit/assignment/users-64px.png"))); // NOI18N
        userLogin.setText("User Login");
        userLogin.setToolTipText("click to login");
        userLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLoginMouseClicked(evt);
            }
        });

        movieSchedule.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        movieSchedule.setForeground(new java.awt.Color(242, 175, 41));
        movieSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topupit/assignment/video-player-64px.png"))); // NOI18N
        movieSchedule.setText(" Movie Schedule");
        movieSchedule.setToolTipText("movie schedule");
        movieSchedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        movieSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieScheduleMouseClicked(evt);
            }
        });

        upcomingMovies.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        upcomingMovies.setForeground(new java.awt.Color(242, 175, 41));
        upcomingMovies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upcomingMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topupit/assignment/next-64px.png"))); // NOI18N
        upcomingMovies.setText(" Upcoming Movies");
        upcomingMovies.setToolTipText("upcoming movies");
        upcomingMovies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upcomingMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upcomingMoviesMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(173, 52, 62));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topupit/assignment/admin-with-cogwheels-64px-2.png"))); // NOI18N
        jLabel1.setText("Admin Login Panel");
        jLabel1.setToolTipText("admin panel");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(userLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(movieSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(upcomingMovies))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movieSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upcomingMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLoginMouseClicked
        System.out.println("User Login Window");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userLoginWindow().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_userLoginMouseClicked

    private void movieScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieScheduleMouseClicked
        System.out.println("Movie Schedule Window");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movieScheduleWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_movieScheduleMouseClicked

    private void upcomingMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcomingMoviesMouseClicked
        System.out.println("Upcoming Movies WIndow");
    }//GEN-LAST:event_upcomingMoviesMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.out.println("Admin Panel Window");
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new adminLoginPanel().setVisible(true);
            }
        });
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new mainWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel movieSchedule;
    private javax.swing.JLabel title;
    private javax.swing.JLabel upcomingMovies;
    private javax.swing.JLabel userLogin;
    // End of variables declaration//GEN-END:variables
}
